### ISSUE TITLE
Что-то непонятное

### ISSUE THREAD

**Issue by alexmikhalevich** [kgrosul/game_interface#1]
А это что такое и зачем оно здесь?
 https://github.com/kgrosul/project/blob/43a5c36e9e48d9d65f95da3e08291e7d67485d2c/test.cpp#L344

**Comment by kgrosul** [comment]
@maked0n Вроде бы исправил. Все действия, связанный с вводом/выводом были вынесены в отдельные классы, необходимость в этой строке отпала.
