### ISSUE TITLE
Обработка нулевого указателя

### ISSUE THREAD

**Issue by alexmikhalevich** [kgrosul/game_interface#2]
А если builder уже разрушен?
 https://github.com/kgrosul/project/blob/43a5c36e9e48d9d65f95da3e08291e7d67485d2c/ships.cpp#L19

**Comment by kgrosul** [comment]
@maked0n А как это вообще по-хорошему надо обрабатывать? В том смысле, что должно произойти, если был передан нулевой указатель? Программа должна завершиться с соответствующей ошибкой или что-то иное?

**Comment by alexmikhalevich** [comment]
по-хорошему, лучше пользоваться умными указателями
однако, есть следующая практика: при разрушении объекта указатель делают равным nullptr. теперь мы во всех местах можем делать assert(my_ptr != nullptr). то есть, если условие выполнено, мы получим ошибку в рантайме.

**Comment by kgrosul** [comment]
@maked0n постарался исправить. Теперь там std::schared_ptr
