### ISSUE TITLE
Раздутый класс

### ISSUE THREAD

**Issue by alexmikhalevich** [kgrosul/game_interface#3]
Не лучше ли эти поля вынести в соответствующие классы?
А то сейчас тут какая-то помойка. https://github.com/kgrosul/project/blob/43a5c36e9e48d9d65f95da3e08291e7d67485d2c/game.h#L145

**Comment by alexmikhalevich** [comment]
UPD: этот класс вообще тебе тут не нужен. Выглядит, как попытка притянуть синглтон за уши.

**Comment by kgrosul** [comment]
@maked0n Синглтон удален. Теперь там просто статические переменные в необходимых namespace'ах.
