### ISSUE TITLE
IO в неподходящем месте

### ISSUE THREAD

**Issue by alexmikhalevich** [kgrosul/game_interface#5]
Зачем у тебя везде в коде cin и cout? То, как это сделано сейчас, плохо со многих точек зрения. Самое основное:  

1. Ты будешь делать GUI? Если да, то зачем тебе еще и печатать все? Или потом нужно будет все удалять?  
2. Какой-нибудь CHouse совершенно точно не должен уметь себя печатать, это нарушение SRP. Если уж так нужно - заведи для этого отдельный класс.

**Comment by kgrosul** [comment]
@maked0n GUI делать вроде не планирую.  Все такие функции вынесены в специальные классы.
